create:
				go run create.go $(b)
listo:
				go run list_object.go $(b)
listb: 
				go run list_bucket.go
deleteb:
				go run delete_bucket.go $(b)
deleteo:
				go run delete_object.go $(b)
upload:
				go run upload.go $(b) $(o) 
