

client:
	curl "localhost:8000/add?item=shirt&price=20"
	curl "localhost:8000/add?item=shirt&price=15"
	curl "localhost:8000/add?item=dress&price=25"
	curl "localhost:8000/list"
	curl "localhost:8000/update?item=shirt&price=10"
	curl "localhost:8000/list"
	curl "localhost:8000/add?item=shoes&price=35"
	curl "localhost:8000/list"
	curl "localhost:8000/delete?item=shoes"
	curl "localhost:8000/list"
