go:
	go run webserver.go
list:
	curl "http://localhost:8000/list"

create:
	curl "http://localhost:8000/create?item=$(item)&price=$(price)"
update:
	curl "http://localhost:8000/update?item=$(item)&price=$(price)"
delete:
	curl "http://localhost:8000/delete?item=$(item)"
price:
	curl "http://localhost:8000/price?item=$(item)"



